CREATE TABLE VARIABLES(
	ID INT PRIMARY KEY,
	CATEGORIA VARCHAR(255),
	VALOR VARCHAR(255)
);

INSERT INTO VARIABLES (ID, CATEGORIA, VALOR) VALUES (1, 'TIPO_PRODUCTO', 'CAMISETA');
INSERT INTO VARIABLES (ID, CATEGORIA, VALOR) VALUES (2, 'TIPO_PRODUCTO', 'VASOS');
INSERT INTO VARIABLES (ID, CATEGORIA, VALOR) VALUES (3, 'TIPO_PRODUCTO', 'COMICS');
INSERT INTO VARIABLES (ID, CATEGORIA, VALOR) VALUES (4, 'TIPO_PRODUCTO', 'JUGUETES');
INSERT INTO VARIABLES (ID, CATEGORIA, VALOR) VALUES (5, 'TIPO_PRODUCTO', 'SUPERHEROES');
INSERT INTO VARIABLES (ID, CATEGORIA, VALOR) VALUES (6, 'MOVIMIENTO', 'SALIDA');
INSERT INTO VARIABLES (ID, CATEGORIA, VALOR) VALUES (7, 'MOVIMIENTO', 'INGRESO');
INSERT INTO VARIABLES (ID, CATEGORIA, VALOR) VALUES (8, 'TIPO_USUARIO', 'ADMIN');
INSERT INTO VARIABLES (ID, CATEGORIA, VALOR) VALUES (9, 'TIPO_USUARIO', 'CLIENTE');

CREATE TABLE PRODUCTOS(
	ID INT PRIMARY KEY,
	ID_TIPO INT,
	REFERENCIA VARCHAR(255),
	PRECIO INT,
	STOCK INT
);

INSERT INTO PRODUCTOS (ID, ID_TIPO, REFERENCIA, PRECIO, STOCK) VALUES (1, 1, 'Camiseta Verde', 25000, 3);
INSERT INTO PRODUCTOS (ID, ID_TIPO, REFERENCIA, PRECIO, STOCK) VALUES (2, 2, 'Vaso Plastico', 5300, 10);
INSERT INTO PRODUCTOS (ID, ID_TIPO, REFERENCIA, PRECIO, STOCK) VALUES (3, 5, 'Gorra de Batman', 30000, 2);
INSERT INTO PRODUCTOS (ID, ID_TIPO, REFERENCIA, PRECIO, STOCK) VALUES (4, 5, 'Tula de Ironman', 15000, 4);

CREATE TABLE USUARIOS(
	ID INT PRIMARY KEY,
	ID_TIPO INT,
	NOMBRE VARCHAR(255),
	USERNAME VARCHAR(255),
	CLAVE VARCHAR(255)
);

INSERT INTO USUARIOS (ID, ID_TIPO, NOMBRE, USERNAME, CLAVE) VALUES (1, 8, 'Manuela Loaiza', 'mloaiza', 'manu123');
INSERT INTO USUARIOS (ID, ID_TIPO, NOMBRE, USERNAME, CLAVE) VALUES (2, 9, 'Pepita Perez', 'pperez', 'pepa123');

CREATE TABLE KARDEX(
	ID INT PRIMARY KEY,
	FECHA DATE,
	ID_MOVIMIENTO INT,
	ID_PRODUCTO INT,
	CANTIDAD INT,
	PRECIO INT
);
ALTER TABLE KARDEX ALTER COLUMN ID INT AUTO_INCREMENT;